version: '3.4'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
  lambo:
    image: lambo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/data
    env_file:
      - .env
    depends_on:
      - db