[tool.poetry]
name = "lambo"
version = "0.1.0"
description = ""
authors = ["HKGx <19597269+HKGx@users.noreply.github.com>"]

[tool.poetry.scripts]
lambo = 'lambo:main'

[tool.poetry.dependencies]
python = "^3.10"
py-cord = "^1.7.3"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
tortoise-orm = {extras = ["aiosqlite"], version = "^0.17.8"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
